name: Build Docker Images

on:
  pull_request:
    paths-ignore:
      - "*.md"
      - "binder/**"
      - "docs/**"
      - "examples/**"
      - ".pre-commit-config.yaml"
  push:
    branches:
      - master
      - main
    paths-ignore:
      - "*.md"
      - "binder/**"
      - "docs/**"
      - "examples/**"
      - ".pre-commit-config.yaml"

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: >
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.pull_request.title, 'ci skip')
    steps:
      - name: Clone Main Repo
        uses: actions/checkout@v2
        with:
          path: main
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          make -C main dev-env
      - name: Build Docker Images
        run: make -C main build-test-all
        env:
          # Full logs for CI build
          BUILDKIT_PROGRESS: plain
      - name: Clone Wiki
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
      - name: Run Post-Build Hooks
        run: make -C main hook-all
      - name: Push Wiki to GitHub
        if: github.ref == 'refs/heads/master'
        # Pass GITHUB_REPOSITORY directly to avoid conflict with GitHub Actions built-in env var
        run: make -C main git-commit GITHUB_REPOSITORY='${{github.repository}}.wiki'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          LOCAL_PATH: ../wiki
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Push Images to DockerHub
        if: github.ref == 'refs/heads/master'
        run: make -C main push-all
